### ISSUE TITLE
Login fails if email not checked

### ISSUE THREAD

**Issue by tvansteenburgh** [juju-solutions/review-queue#26]
When logging in through Ubuntu SSO, the user needs to share (check the boxes on the interstitial Personal Data Request page on login.ubuntu.com) their name, username, and email address, otherwise bad things happen (see traceback below).

See if there's a way to make these boxes be checked by default.

```
Traceback (most recent call last):
  File "/opt/reviewqueue/.venv/local/lib/python2.7/site-packages/pyramid_exclog/__init__.py", line 111, in exclog_tween
    return handler(request)
  File "/opt/reviewqueue/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/opt/reviewqueue/.venv/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/opt/reviewqueue/.venv/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/opt/reviewqueue/.venv/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/opt/reviewqueue/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/opt/reviewqueue/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 507, in _requestonly_view
    response = view(request)
  File "/opt/reviewqueue/reviewqueue/views/auth.py", line 55, in login_callback
    **user_data)
  File "/opt/reviewqueue/reviewqueue/db.py", line 56, in create_user
    kw['nickname']),
  File "/opt/reviewqueue/.venv/local/lib/python2.7/site-packages/lazr/restfulclient/resource.py", line 514, in load
    raise ValueError("%s doesn't serve a JSON document." % url)
ValueError: https://api.launchpad.net/1.0/~None doesn't serve a JSON document.
```

**Comment by tvansteenburgh** [comment]
Fixed by e6835b54204e9c3ca80ca1f50b5b3d349080f063
