### ISSUE TITLE
Test Results: Arg Stack Trace

### ISSUE THREAD

**Issue by arosales** [juju-solutions/review-queue#48]
When looking at the review:
https://review.jujucharms.com/reviews/21

I see 3 test results:
http://juju-ci.vapour.ws/job/charm-bundle-test-lxc/6387/console
http://juju-ci.vapour.ws/job/charm-bundle-test-gce/63/console
https://review.jujucharms.com/revision_tests/106

The first 2 errors looks to be infrastructure related, stack trace with bundle tester on missing args, the last one is confusing as it lists cassandra results which isn't related to this review.

-thanks,
Antonio

**Comment by arosales** [comment]
For the LXC test we look to bootstrap ok on 1.25, but then as we prepare to run the bundle we get a stack trace causing a non-zero return:

```
Traceback (most recent call last):
  File "/usr/local/bin/bundletester", line 9, in <module>
    load_entry_point('bundletester==0.9.1', 'console_scripts', 'bundletester')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 12, in <module>
    from bundletester import (
  File "/usr/local/lib/python2.7/dist-packages/bundletester/runner.py", line 8, in <module>
    from bundletester.spec import Suite
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 8, in <module>
    from bundletester import (config, models, utils)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/models.py", line 6, in <module>
    from bundletester import utils
  File "/usr/local/lib/python2.7/dist-packages/bundletester/utils.py", line 5, in <module>
    from deployer.config import ConfigStack
  File "/usr/lib/python2.7/dist-packages/deployer/config.py", line 13, in <module>
    from .deployment import Deployment
  File "/usr/lib/python2.7/dist-packages/deployer/deployment.py", line 14, in <module>
    from .service import Service, ServiceUnitPlacementV3, ServiceUnitPlacementV4
  File "/usr/lib/python2.7/dist-packages/deployer/service.py", line 9, in <module>
    if get_juju_major_version() == 1:
  File "/usr/lib/python2.7/dist-packages/deployer/utils.py", line 264, in get_juju_major_version
    ["juju", "--version"], log).split(b'.')[0])
  File "/usr/lib/python2.7/dist-packages/deployer/utils.py", line 287, in _check_call
    params, cwd=cwd, stderr=stderr, env=os.environ, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
+ EXIT_STATUS=1
```

Similar error for GCE:

```
Traceback (most recent call last):
  File "/usr/local/bin/bundletester", line 9, in <module>
    load_entry_point('bundletester==0.9.1', 'console_scripts', 'bundletester')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 12, in <module>
    from bundletester import (
  File "/usr/local/lib/python2.7/dist-packages/bundletester/runner.py", line 8, in <module>
    from bundletester.spec import Suite
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 8, in <module>
    from bundletester import (config, models, utils)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/models.py", line 6, in <module>
    from bundletester import utils
  File "/usr/local/lib/python2.7/dist-packages/bundletester/utils.py", line 5, in <module>
    from deployer.config import ConfigStack
  File "/usr/lib/python2.7/dist-packages/deployer/config.py", line 13, in <module>
    from .deployment import Deployment
  File "/usr/lib/python2.7/dist-packages/deployer/deployment.py", line 14, in <module>
    from .service import Service, ServiceUnitPlacementV3, ServiceUnitPlacementV4
  File "/usr/lib/python2.7/dist-packages/deployer/service.py", line 9, in <module>
    if get_juju_major_version() == 1:
  File "/usr/lib/python2.7/dist-packages/deployer/utils.py", line 264, in get_juju_major_version
    ["juju", "--version"], log).split(b'.')[0])
  File "/usr/lib/python2.7/dist-packages/deployer/utils.py", line 287, in _check_call
    params, cwd=cwd, stderr=stderr, env=os.environ, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
+ EXIT_STATUS=1
```

**Comment by tvansteenburgh** [comment]
I looked into this briefly and am fairly certain that these errors were caused by a broken build of charmbox (which has since been fixed).
