### ISSUE TITLE
pkgresources no path.py module found

### ISSUE THREAD

**Issue by adam-stokes** [juju-solutions/review-queue#52]
```
Digest: sha256:a9d39b1a5d71c1335d7ca82ea2453732535d0f1b4bf191faa4bc084d69fad2df
Status: Downloaded newer image for jujusolutions/charmbox:latest
+ sudo docker run --rm -u ubuntu -e HOME=/home/ubuntu -e JUJU_HOME=/home/ubuntu/.juju -w /home/ubuntu -v /tmp/tmp.4al8jt5cBS:/home/ubuntu/.juju -v /tmp/tmp.f3AOYdtdyK/.deployer-store-cache:/home/ubuntu/.juju/.deployer-store-cache -v /tmp/tmp.C6VWR6gs7b:/home/ubuntu/charm-repo -v /tmp/tmp.f3AOYdtdyK:/tmp/tmp.f3AOYdtdyK -v /tmp/tmp.f3AOYdtdyK/ssh:/home/ubuntu/.ssh -t jujusolutions/charmbox:latest sh -c 'bzr whoami '\''Tim Van Steenburgh <tvansteenburgh@gmail.com>'\'' && sudo bundletester -F -e charm-testing-gce -t cs:~adam-stokes/xenial/znc-1 -l DEBUG -v -r json -o /tmp/tmp.f3AOYdtdyK/results.json '
Traceback (most recent call last):
  File "/usr/local/bin/bundletester", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 642, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'path.py<=8.1.2' distribution was not found and is required by charm-tools
+ EXIT_STATUS=1
```
http://juju-ci.vapour.ws/job/charm-bundle-test-gce/101/console

**Comment by tvansteenburgh** [comment]
Side effect of https://github.com/juju/charm-tools/issues/274

**Comment by adam-stokes** [comment]
Still broken with same error now that the above linked bug is fixed
