### ISSUE TITLE
ValueError in refresh_revisions (not in list)

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/review-queue#82]
From error emails:

```
Task reviewqueue.tasks.refresh_review with id da300b1f-67b0-4a9a-90e1-802f38d2df91 raised exception:
'ValueError("u\'cs:~ibmcharmers/trusty/ibm-wxs-catalog-5\' is not in list",)'


Task was called with args: (<reviewqueue.models.review.Review object at 0x7f2170ad0bd0>,) kwargs: {}.

The contents of the full traceback was:

Traceback (most recent call last):
  File "/opt/reviewqueue/.venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/reviewqueue/.venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/reviewqueue/reviewqueue/tasks.py", line 33, in refresh_review
    review.refresh_revisions(celery.settings)
  File "/opt/reviewqueue/reviewqueue/models/review.py", line 183, in refresh_revisions
    remote_revisions[0:remote_revisions.index(current_revision)])
ValueError: u'cs:~ibmcharmers/trusty/ibm-wxs-catalog-5' is not in list
```

This is probably a corner case in the charm store, but we should handle it gracefully.

**Comment by johnsca** [comment]
This has already been fixed but not released.
